"""Compliance audit trail — "which record went where, and when" (#1100).

Reverse ETL has a liability shape most data-loading tools don't: it
actively pushes data *out* to third-party destinations. This Protocol
answers the question a GDPR/compliance request can ask ("did record X go
to destination Y, and when") with a queryable, retention-managed delivery
log — differentiated from the closest prior art (Hightouch's
`hightouch_audit.Changelog`) by owning the retention/purge contract as a
first-class feature instead of leaving unbounded PII retention entirely to
the customer, per this issue's own competitive research.

**Not the same thing as `drt.observability.audit.AuditLogger`** (ADR 0008,
#299) — that Protocol covers two enterprise config/secret-access events
(`config_changed`/`secret_accessed`), no-op by default, and has nothing to
do with record delivery. Named ``ComplianceAuditTrail`` specifically to
avoid that collision.

Only a warehouse backend implements this Protocol, for the same reason
``IdempotencyLedger`` (#1099) is warehouse-only: see
``drt/state/warehouse.py``'s module docstring. ``StateBundle.audit_trail``
is ``None`` unless ``state.backend: warehouse`` and
``state.audit_trail.enabled: true`` are both set.

**Field capture happens after ``sync.mask`` (#427).** Logging the pre-mask
raw value would recreate the exact PII liability ``sync.mask`` exists to
prevent, in a second table, and would misrepresent "what went where" —
the destination never received the pre-mask value. A sync with no
``sync.mask`` configured logs whatever raw values ``state.audit_trail.
fields`` names, for the full ``retain_days`` window — a deliberate
operator choice, not an oversight (see ``AuditTrailConfig``'s docstring).

Project-wide, not per-sync: unlike #1099's `sync.idempotency_key`, this is
a compliance policy an individual sync shouldn't be able to quietly opt
out of once the project turns it on.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable


@dataclass
class AuditEntry:
    """One delivered record's logged identity, for one ``log_delivered`` call.

    ``record_key`` and ``fields`` are both derived from
    ``state.audit_trail.fields`` — the same list, so there is no separate
    key-template config surface for this feature (unlike #897's
    ``destination.idempotency_key`` / #1099's ``sync.idempotency_key``).
    ``record_key`` is the ``":"``-joined string form of every configured
    field's value (empty string if none were present on this record);
    ``fields`` holds only the subset of configured fields that were
    actually present, so a field absent from a particular sync's schema is
    simply missing from the JSON rather than null-padded.
    """

    record_key: str
    fields: dict[str, Any]


@runtime_checkable
class ComplianceAuditTrail(Protocol):
    """Optional warehouse capability: log delivered records for compliance.

    Stability: New in #1100 — not yet frozen (see ADR 0007).

    Like ``IdempotencyLedger``, keys on ``sync_name`` alone — the same
    non-novel per-project-namespace limitation documented on
    ``PostgresWarehouseStateStore``.
    """

    def log_delivered(
        self,
        sync_name: str,
        run_id: str | None,
        sync_run_id: str | None,
        destination_type: str,
        entries: list[AuditEntry],
        delivered_at: str,
    ) -> None:
        """Append one audit row per entry for records just delivered.

        Called only for records a batch's ``destination.load()`` actually
        reported success for — the same successful-indices computation
        #1099's ``mark_delivered`` call already needs, shared via
        ``engine/sync.py``'s ``_successful_indices`` helper. ``run_id`` is
        ``None`` for library callers that don't track an invocation-level
        id (see ``run_sync()``'s own docstring). ``sync_run_id`` is always
        generated by ``run_sync()`` in practice, but typed ``str | None``
        to match ``SyncResult.sync_run_id``'s own honest optionality rather
        than asserting a guarantee the dataclass field itself doesn't
        enforce — same nullable-in-the-type-system convention
        ``DeadLetter.sync_run_id`` already uses. Best-effort: an audit-log
        write failure must not fail an otherwise-successful sync, so
        implementations log and swallow rather than raise — same contract
        as ``HistoryStore.append``.
        """
        ...

    def prune(self, sync_name: str, retain_days: int) -> int:
        """Delete this sync's audit rows older than ``retain_days``.

        Returns the number of rows removed. Same call-site pattern as
        ``IdempotencyLedger.prune`` / ``HistoryStore.prune`` — the engine
        calls this once per non-dry-run sync, answering this issue's own
        open question about where purge is triggered from with the
        precedent already shipped for #1099's ledger, rather than a
        separate CLI surface.
        """
        ...
