"""Pydantic models for drt project and sync configuration.

Phase 1 of #721 split this formerly ~1300-line module into cohesive submodules
(:mod:`~drt.config.base`, :mod:`~drt.config.destinations_sql`,
:mod:`~drt.config.destinations_saas`, :mod:`~drt.config.destinations_storage`,
:mod:`~drt.config.sync_options`). This module re-exports the full public surface
so every ``from drt.config.models import X`` keeps working unchanged.

``__all__`` below IS that public surface and is **required**: under mypy strict
``no_implicit_reexport`` a merely re-imported name is not considered exported,
so single-file type-checking would pass while the 135 import sites fail. Keep
``__all__`` in sync when adding or removing a config name.
"""

from __future__ import annotations

from drt.config.base import (
    ApiKeyAuth,
    AuthConfig,
    BasicAuth,
    BearerAuth,
    CursorPaginationConfig,
    HistoryConfig,
    LinkHeaderPaginationConfig,
    LookupConfig,
    OAuth2ClientCredentialsAuth,
    OffsetPaginationConfig,
    PaginationConfig,
    ProjectConfig,
    RestIncrementalConfig,
    RetryConfig,
    SourceConfig,
    SslConfig,
)
from drt.config.destinations_saas import (
    AirtableDestinationConfig,
    AmplitudeDestinationConfig,
    DiscordDestinationConfig,
    EmailSmtpDestinationConfig,
    GitHubActionsDestinationConfig,
    GoogleAdsDestinationConfig,
    GoogleSheetsDestinationConfig,
    HubSpotDestinationConfig,
    IntercomDestinationConfig,
    JiraDestinationConfig,
    KlaviyoDestinationConfig,
    LinearDestinationConfig,
    MixpanelDestinationConfig,
    NotionDestinationConfig,
    RestApiDestinationConfig,
    SalesforceBulkDestinationConfig,
    SendGridDestinationConfig,
    SlackDestinationConfig,
    StagedUploadDestinationConfig,
    StagedUploadPhaseConfig,
    StagedUploadPollConfig,
    TeamsDestinationConfig,
    TwilioDestinationConfig,
    ZendeskDestinationConfig,
)
from drt.config.destinations_sql import (
    BaseSqlDestinationConfig,
    BigQueryDestinationConfig,
    ClickHouseDestinationConfig,
    DatabricksDestinationConfig,
    ElasticsearchDestinationConfig,
    MySQLDestinationConfig,
    PostgresDestinationConfig,
    SnowflakeDestinationConfig,
)
from drt.config.destinations_storage import (
    AzureBlobDestinationConfig,
    FileDestinationConfig,
    GCSDestinationConfig,
    ParquetDestinationConfig,
    S3DestinationConfig,
)
from drt.config.sync_options import (
    AcceptedValuesTest,
    AlertItem,
    AlertsConfig,
    DestinationConfig,
    DLQConfig,
    FreshnessTest,
    MaskRule,
    MaskSpec,
    MirrorConfig,
    NotNullTest,
    RateLimitConfig,
    RowCountTest,
    SlackAlertConfig,
    SyncConfig,
    SyncOptions,
    SyncTest,
    UniqueTest,
    WatermarkConfig,
    WebhookAlertConfig,
)

__all__ = [
    "AcceptedValuesTest",
    "AirtableDestinationConfig",
    "AlertItem",
    "AlertsConfig",
    "AmplitudeDestinationConfig",
    "ApiKeyAuth",
    "AuthConfig",
    "AzureBlobDestinationConfig",
    "BaseSqlDestinationConfig",
    "BasicAuth",
    "BearerAuth",
    "BigQueryDestinationConfig",
    "ClickHouseDestinationConfig",
    "CursorPaginationConfig",
    "DLQConfig",
    "DatabricksDestinationConfig",
    "DestinationConfig",
    "DiscordDestinationConfig",
    "ElasticsearchDestinationConfig",
    "EmailSmtpDestinationConfig",
    "FileDestinationConfig",
    "FreshnessTest",
    "GCSDestinationConfig",
    "GitHubActionsDestinationConfig",
    "GoogleAdsDestinationConfig",
    "GoogleSheetsDestinationConfig",
    "HistoryConfig",
    "HubSpotDestinationConfig",
    "IntercomDestinationConfig",
    "JiraDestinationConfig",
    "KlaviyoDestinationConfig",
    "LinearDestinationConfig",
    "LinkHeaderPaginationConfig",
    "LookupConfig",
    "MaskRule",
    "MaskSpec",
    "MirrorConfig",
    "MixpanelDestinationConfig",
    "MySQLDestinationConfig",
    "NotNullTest",
    "NotionDestinationConfig",
    "OAuth2ClientCredentialsAuth",
    "OffsetPaginationConfig",
    "PaginationConfig",
    "ParquetDestinationConfig",
    "PostgresDestinationConfig",
    "ProjectConfig",
    "RateLimitConfig",
    "RestApiDestinationConfig",
    "RestIncrementalConfig",
    "RetryConfig",
    "RowCountTest",
    "S3DestinationConfig",
    "SalesforceBulkDestinationConfig",
    "SendGridDestinationConfig",
    "SlackAlertConfig",
    "SlackDestinationConfig",
    "SnowflakeDestinationConfig",
    "SourceConfig",
    "SslConfig",
    "StagedUploadDestinationConfig",
    "StagedUploadPhaseConfig",
    "StagedUploadPollConfig",
    "SyncConfig",
    "SyncOptions",
    "SyncTest",
    "TeamsDestinationConfig",
    "TwilioDestinationConfig",
    "UniqueTest",
    "WatermarkConfig",
    "WebhookAlertConfig",
    "ZendeskDestinationConfig",
]
